name: Deploy to Azure Functions Staging

on:
  push:
    branches: [ main, cloud-migration ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: pokedata-func
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './PokeDataFunc'
  NODE_VERSION: '22.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './PokeDataFunc/package-lock.json'

    - name: 'Install dependencies'
      run: npm ci
      working-directory: ./PokeDataFunc

    - name: 'Build TypeScript'
      run: npm run build
      working-directory: ./PokeDataFunc

    - name: 'Upload artifact for deployment job'
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: ./PokeDataFunc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: 'Download artifact from build job'
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Functions Staging'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'staging'
        package: '.'
