name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: pokedata-func
  AZURE_FUNCTIONAPP_SLOT_NAME: pokedata-func-staging
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci
      working-directory: PokeDataFunc

    - name: Build
      run: npm run build
      working-directory: PokeDataFunc

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: pokedata-func
        package: PokeDataFunc  # Point to the PokeDataFunc directory
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        slot-name: staging
